### ISSUE TITLE
Question: different speed during stepping in a loop

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [ostrosco/adafruit_motorkit#3]
When i use the example:
https://github.com/ostrosco/adafruit_motorkit/blob/master/examples/stepper.rs
and go for microstepping of a larger number of steps, e.g. one full rortation (200 steps * num_microsteps). It seems that the motor has a static speed for some seconds and reduces to a lower speed shortly. This second lowered speed is than also static until i power off.

Did you encounter also some speed changes on longer runs? It seems to be not torque dependend, since even the motor only with a little flag out of tape shows this behavior.

**Comment by ostrosco** [comment]
I've not noticed it but that doesn't mean there isn't a problem. Let me see if I can reproduce it sometime this weekend.

**Comment by cguentherTUChemnitz** [comment]
I think i found the problem. The raspberry pi seems to bind the ic2 speed to the clock speed of the cpu. As soon as the cpu does dynamic clocking it changes the i2c speed and therefore the motorspeed here. My solution was to fix the raspi clock speed, which in turn fixed this stepping speed here.
